package Siam;

public interface Constantes {
    int NOMBRE_CASE_INI = 5;
    int TAILLE_SPRITE = 128;
    int HAUTEUR_BOUTON = 100;
    int LARGEUR_BOUTON = 200;
    int TAILLE_SPRITE_FLECHE = 50;
    int BORDURE_FENETRE = 150;
    int HAUTEUR_FENETRE_INI = TAILLE_SPRITE*NOMBRE_CASE_INI+BORDURE_FENETRE;
    int LARGEUR_FENETRE_INI = HAUTEUR_FENETRE_INI + 275;
    int LARGEUR_AFFICHAGE_PLATEAU = TAILLE_SPRITE*NOMBRE_CASE_INI+BORDURE_FENETRE;
    int HAUTEUR_AFFICHAGE_PLATEAU = LARGEUR_AFFICHAGE_PLATEAU;
}
