package Siam;

public interface Constantes {
    int NOMBRE_CASE_INI = 5;
    int TAILLE_SPRITE = 128;
    int BORDURE_FENETRE = 100;
    int LARGEUR_AFFICHAGE_PLATEAU = TAILLE_SPRITE * NOMBRE_CASE_INI + BORDURE_FENETRE;
    int HAUTEUR_AFFICHAGE_PLATEAU = LARGEUR_AFFICHAGE_PLATEAU;
    int HAUTEUR_FENETRE = LARGEUR_AFFICHAGE_PLATEAU;
    int LARGEUR_FENETRE = HAUTEUR_FENETRE + 300;
    int NOMBRE_DE_PIECE_POSEE_MAX_VARIANTE = 6;
}
